name: CI/CD Pipeline

# Define triggers for the workflow
on:
  push:
    branches:
      - main  # Run on push to main branch
  pull_request:
    branches:
      - main  # Run on pull requests to main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Define build steps
      - name: Install Node.js dependencies
        run: npm install

      # Define test steps
      - name: Run linting
        run: npm run lint

      - name: Run unit tests with environment variables
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
          SAFE_BROWSING_API_KEY: ${{ secrets.SAFE_BROWSING_API_KEY }}
        run: npm test

      - name: Run unit tests
        run: npm test

      # Define deployment steps
      # - name: Build Docker image
      #   run: docker build -t generate-qr .
      
      # - name: Push Docker image to Docker Hub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}
      
      # - name: Push Docker image
      #   run: docker push generate-qr

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build and test
        uses: docker/build-push-action@v5
        with:
          context: .
          target: test
          load: true
      
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          target: prod
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}:latest